project:
  type: website
  output-dir: docs
  resources: 
    - "./Software"
    - "./pinion"

website:
  title: "AAElectronics"
  sidebar:
    style: "docked"
    contents:
      - href: documentation/yulc/yulc.qmd
        text: YULC
      - href: documentation/esp360/esp360.qmd
        text: ESP 360 REMOTE
      - href: documentation/flashing/flashing.qmd
        text: Flashing

format:
  html:
    theme: 
      light: cosmo
      dark: cosmo
    css: styles.css
    toc: true



